/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import java.sql.*;
import db.dbcon;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ahmar
 */
public class management extends javax.swing.JFrame {

    /**
     * Creates new form management
     */
    public management() {
        initComponents();
    }
    String trainid,trainname,departure,arrival,date,dtime,atime,erate,brate,acrate,eseats,bseats,acseats;
    String tbtrainid,tbtrainname,tbdeparture,tbarrival,tbdate,tbdtime,tbatime;
    String wintrainid,wintrainname,windeparture,winarrival,windate,windtime,winatime;
    int tberate,tbbrate,tbacrate,tbeseats,tbbseats,tbacseats;
    int winerate,winbrate,winacrate,wineseats,winbseats,winacseats;
    String id;
    String bticketid,bname,bcnic,bnumber,bemail,bfare,bclass,bookseats,bfrom,bto,bdate,btrainid,btrainname,
            bdtime,batime;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnltop = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        pnlside = new javax.swing.JPanel();
        managepanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bookingpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlmanage = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtftrainid = new javax.swing.JTextField();
        txtftrainname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfdeparture = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtfarrival = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtfdate = new javax.swing.JTextField();
        txtfdtime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtfatime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtferate = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfbrate = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtfacrate = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtfeseats = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtfbseats = new javax.swing.JTextField();
        txtfacseats = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btninsert = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabledata = new javax.swing.JTable();
        lblerror = new javax.swing.JLabel();
        btnrefresh = new javax.swing.JButton();
        pnlbooking = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblbooking = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnltop.setBackground(new java.awt.Color(23, 42, 48));
        pnltop.setForeground(new java.awt.Color(255, 255, 255));
        pnltop.setPreferredSize(new java.awt.Dimension(962, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restore.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/train logo.png"))); // NOI18N
        jLabel19.setText("TRAIN MANAGEMENT SYSTEM");

        javax.swing.GroupLayout pnltopLayout = new javax.swing.GroupLayout(pnltop);
        pnltop.setLayout(pnltopLayout);
        pnltopLayout.setHorizontalGroup(
            pnltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 788, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        pnltopLayout.setVerticalGroup(
            pnltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnltopLayout.createSequentialGroup()
                .addGroup(pnltopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 5, Short.MAX_VALUE))
            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnltop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, -1));

        pnlside.setBackground(new java.awt.Color(29, 61, 72));
        pnlside.setPreferredSize(new java.awt.Dimension(240, 520));

        managepanel.setBackground(new java.awt.Color(29, 61, 72));
        managepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managepanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                managepanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                managepanelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Schedule");

        javax.swing.GroupLayout managepanelLayout = new javax.swing.GroupLayout(managepanel);
        managepanel.setLayout(managepanelLayout);
        managepanelLayout.setHorizontalGroup(
            managepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );
        managepanelLayout.setVerticalGroup(
            managepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(managepanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        bookingpanel.setBackground(new java.awt.Color(29, 61, 72));
        bookingpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bookingpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookingpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookingpanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Booking");

        javax.swing.GroupLayout bookingpanelLayout = new javax.swing.GroupLayout(bookingpanel);
        bookingpanel.setLayout(bookingpanelLayout);
        bookingpanelLayout.setHorizontalGroup(
            bookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
        );
        bookingpanelLayout.setVerticalGroup(
            bookingpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookingpanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout pnlsideLayout = new javax.swing.GroupLayout(pnlside);
        pnlside.setLayout(pnlsideLayout);
        pnlsideLayout.setHorizontalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlsideLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(managepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bookingpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(831, Short.MAX_VALUE))
        );
        pnlsideLayout.setVerticalGroup(
            pnlsideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(managepanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookingpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(pnlside, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1240, 40));

        pnlmanage.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Train ID");

        txtftrainid.setBackground(new java.awt.Color(219, 219, 219));
        txtftrainid.setForeground(new java.awt.Color(51, 51, 51));
        txtftrainid.setBorder(null);

        txtftrainname.setBackground(new java.awt.Color(219, 219, 219));
        txtftrainname.setForeground(new java.awt.Color(51, 51, 51));
        txtftrainname.setBorder(null);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Train Name");

        txtfdeparture.setBackground(new java.awt.Color(219, 219, 219));
        txtfdeparture.setForeground(new java.awt.Color(51, 51, 51));
        txtfdeparture.setBorder(null);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Departure");

        txtfarrival.setBackground(new java.awt.Color(219, 219, 219));
        txtfarrival.setForeground(new java.awt.Color(51, 51, 51));
        txtfarrival.setBorder(null);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Arrival");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Date");

        txtfdate.setBackground(new java.awt.Color(219, 219, 219));
        txtfdate.setForeground(new java.awt.Color(51, 51, 51));
        txtfdate.setBorder(null);

        txtfdtime.setBackground(new java.awt.Color(219, 219, 219));
        txtfdtime.setForeground(new java.awt.Color(51, 51, 51));
        txtfdtime.setBorder(null);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Departure Time");

        txtfatime.setBackground(new java.awt.Color(219, 219, 219));
        txtfatime.setForeground(new java.awt.Color(51, 51, 51));
        txtfatime.setBorder(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Arrival Time");

        txtferate.setBackground(new java.awt.Color(219, 219, 219));
        txtferate.setForeground(new java.awt.Color(51, 51, 51));
        txtferate.setBorder(null);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Economy Rate");

        txtfbrate.setBackground(new java.awt.Color(219, 219, 219));
        txtfbrate.setForeground(new java.awt.Color(51, 51, 51));
        txtfbrate.setBorder(null);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Business Rate");

        txtfacrate.setBackground(new java.awt.Color(219, 219, 219));
        txtfacrate.setForeground(new java.awt.Color(51, 51, 51));
        txtfacrate.setBorder(null);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("AC Parlour Rate ");

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Economy Seats");

        txtfeseats.setBackground(new java.awt.Color(219, 219, 219));
        txtfeseats.setForeground(new java.awt.Color(51, 51, 51));
        txtfeseats.setBorder(null);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Business Seats");

        txtfbseats.setBackground(new java.awt.Color(219, 219, 219));
        txtfbseats.setForeground(new java.awt.Color(51, 51, 51));
        txtfbseats.setBorder(null);

        txtfacseats.setBackground(new java.awt.Color(219, 219, 219));
        txtfacseats.setForeground(new java.awt.Color(51, 51, 51));
        txtfacseats.setBorder(null);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("AC Parlou Seats");

        btninsert.setBackground(new java.awt.Color(23, 42, 4));
        btninsert.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btninsert.setForeground(new java.awt.Color(255, 255, 255));
        btninsert.setText("Insert");
        btninsert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 42, 4), 6, true));
        btninsert.setBorderPainted(false);
        btninsert.setFocusPainted(false);
        btninsert.setFocusable(false);
        btninsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btninsertMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btninsertMouseReleased(evt);
            }
        });

        btndelete.setBackground(new java.awt.Color(23, 42, 4));
        btndelete.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btndelete.setForeground(new java.awt.Color(255, 255, 255));
        btndelete.setText("Delete");
        btndelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 42, 4), 6, true));
        btndelete.setBorderPainted(false);
        btndelete.setFocusPainted(false);
        btndelete.setFocusable(false);
        btndelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btndeleteMouseClicked(evt);
            }
        });

        tabledata.setBackground(new java.awt.Color(255, 255, 255));
        tabledata.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        tabledata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "train ID", "Train Name", "Departure", "Arrival", "Date", "Departure Time", "Arrival Time", "Economy Rate", "Business Rate", "AC Parlour Rate", "Economy Seats", "Business Seats", "AC Parlour Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabledata);
        if (tabledata.getColumnModel().getColumnCount() > 0) {
            tabledata.getColumnModel().getColumn(0).setResizable(false);
            tabledata.getColumnModel().getColumn(1).setResizable(false);
            tabledata.getColumnModel().getColumn(2).setResizable(false);
            tabledata.getColumnModel().getColumn(3).setResizable(false);
            tabledata.getColumnModel().getColumn(4).setResizable(false);
            tabledata.getColumnModel().getColumn(5).setResizable(false);
            tabledata.getColumnModel().getColumn(6).setResizable(false);
            tabledata.getColumnModel().getColumn(7).setResizable(false);
            tabledata.getColumnModel().getColumn(8).setResizable(false);
            tabledata.getColumnModel().getColumn(9).setResizable(false);
            tabledata.getColumnModel().getColumn(10).setResizable(false);
            tabledata.getColumnModel().getColumn(11).setResizable(false);
            tabledata.getColumnModel().getColumn(12).setResizable(false);
        }

        lblerror.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lblerror.setForeground(new java.awt.Color(255, 0, 0));

        btnrefresh.setBackground(new java.awt.Color(23, 42, 4));
        btnrefresh.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        btnrefresh.setVisible(false);
        btnrefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnrefresh.setText("Refresh");
        btnrefresh.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 42, 4), 6, true));
        btnrefresh.setBorderPainted(false);
        btnrefresh.setFocusPainted(false);
        btnrefresh.setFocusable(false);
        btnrefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnrefreshMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnrefreshMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnlmanageLayout = new javax.swing.GroupLayout(pnlmanage);
        pnlmanage.setLayout(pnlmanageLayout);
        pnlmanageLayout.setHorizontalGroup(
            pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmanageLayout.createSequentialGroup()
                .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlmanageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlmanageLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(btnrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtftrainid, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtftrainname)
                                .addComponent(txtfdeparture)
                                .addComponent(txtfarrival)
                                .addComponent(txtfdate)
                                .addComponent(txtfdtime)
                                .addComponent(txtfatime)
                                .addComponent(txtferate)
                                .addComponent(txtfbrate)
                                .addComponent(txtfacrate)
                                .addComponent(txtfeseats)
                                .addComponent(txtfbseats)
                                .addComponent(txtfacseats))))
                    .addGroup(pnlmanageLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btninsert, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlmanageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblerror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 876, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlmanageLayout.setVerticalGroup(
            pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlmanageLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlmanageLayout.createSequentialGroup()
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtftrainid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtftrainname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfdeparture, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfarrival, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfdate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfdtime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfatime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtferate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfbrate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfacrate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfeseats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfbseats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfacseats, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblerror)
                        .addGap(2, 2, 2)
                        .addGroup(pnlmanageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btninsert)
                            .addComponent(btndelete)
                            .addComponent(btnrefresh))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(pnlmanage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 500));

        pnlbooking.setBackground(new java.awt.Color(255, 255, 255));
        pnlbooking.setVisible(false);

        tblbooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "Name ", "CNIC", "Number", "Email", "Fare", "Class", "Seats", "From", "To", "Date", "Train ID", "Train Name ", "Departure Time", "Arrival Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblbooking);
        if (tblbooking.getColumnModel().getColumnCount() > 0) {
            tblbooking.getColumnModel().getColumn(0).setResizable(false);
            tblbooking.getColumnModel().getColumn(1).setResizable(false);
            tblbooking.getColumnModel().getColumn(2).setResizable(false);
            tblbooking.getColumnModel().getColumn(3).setResizable(false);
            tblbooking.getColumnModel().getColumn(4).setResizable(false);
            tblbooking.getColumnModel().getColumn(5).setResizable(false);
            tblbooking.getColumnModel().getColumn(6).setResizable(false);
            tblbooking.getColumnModel().getColumn(7).setResizable(false);
            tblbooking.getColumnModel().getColumn(9).setResizable(false);
            tblbooking.getColumnModel().getColumn(10).setResizable(false);
            tblbooking.getColumnModel().getColumn(11).setResizable(false);
            tblbooking.getColumnModel().getColumn(12).setResizable(false);
            tblbooking.getColumnModel().getColumn(13).setResizable(false);
            tblbooking.getColumnModel().getColumn(14).setResizable(false);
        }

        javax.swing.GroupLayout pnlbookingLayout = new javax.swing.GroupLayout(pnlbooking);
        pnlbooking.setLayout(pnlbookingLayout);
        pnlbookingLayout.setHorizontalGroup(
            pnlbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbookingLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlbookingLayout.setVerticalGroup(
            pnlbookingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbookingLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(pnlbooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void managepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepanelMouseEntered
        managepanel.setBackground(new Color(41,86,101));
    }//GEN-LAST:event_managepanelMouseEntered

    private void managepanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepanelMouseExited
        managepanel.setBackground(new Color(29,61,72));
    }//GEN-LAST:event_managepanelMouseExited

    private void bookingpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingpanelMouseEntered
        bookingpanel.setBackground(new Color(41,86,101));
    }//GEN-LAST:event_bookingpanelMouseEntered

    private void bookingpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingpanelMouseExited
        bookingpanel.setBackground(new Color(29,61,72));
    }//GEN-LAST:event_bookingpanelMouseExited

    private void btninsertMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertMousePressed
        tabledata.setModel(new DefaultTableModel(null, new String[]{"Train ID","train name","departure","arrival","date","departure Time","Arrival Time","Economy rate","Business rate","AC Parlour rate","Economy seats","Business seats","AC Parlour seats"}));
    }//GEN-LAST:event_btninsertMousePressed

    private void btninsertMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninsertMouseReleased
        trainid = txtftrainid.getText();
        trainname = txtftrainname.getText();
        departure = txtfdeparture.getText();
        arrival = txtfarrival.getText();
        date = txtfdate.getText();
        dtime = txtfdtime.getText();
        atime = txtfatime.getText();
        erate = txtferate.getText();
        brate = txtfbrate.getText();
        acrate = txtfacrate.getText();
        eseats = txtfeseats.getText();
        bseats = txtfbseats.getText();
        acseats = txtfacseats.getText();
        if( trainid.trim().isEmpty() || acrate.trim().isEmpty() 
        || eseats.trim().isEmpty() || brate.trim().isEmpty() ||date.trim().isEmpty() ||arrival.trim().isEmpty() 
        ||departure.trim().isEmpty() ||atime.trim().isEmpty() ||dtime.trim().isEmpty() ||erate.trim().isEmpty() ||
        bseats.trim().isEmpty() || acseats.trim().isEmpty() || trainname.trim().isEmpty() ){
            lblerror.setText("Please fill all the fields");
            try {
                Connection con = dbcon.getcon();
                String stm = "insert  into train_schedulle  values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement sttm = con.prepareStatement(stm);
                sttm.setString(1,trainid);
                sttm.setString(2,trainname);
                sttm.setString(3,departure);
                sttm.setString(4,arrival);
                sttm.setString(5,date);
                sttm.setString(6,dtime);
                sttm.setString(7,atime);
                sttm.setString(8,erate);
                sttm.setString(9,brate);
                sttm.setString(10,acrate);
                sttm.setString(11,eseats);
                sttm.setString(12,bseats);
                sttm.setString(13,acseats);
                sttm.execute();
                Statement stm1 = con.createStatement();
                String s1 = "select * from train_schedulle";
                ResultSet rs1 = stm1.executeQuery(s1);
                while(rs1.next()){
                    tbtrainid =  rs1.getString("TRAIN_ID");
                    tbtrainname =  rs1.getString("TRAIN_NAME");
                    tbdeparture =  rs1.getString("DEPARTURE");
                    tbarrival =  rs1.getString("ARRIVAL");
                    tbdate =  rs1.getString("DATE");
                    tbdtime =  rs1.getString("DEPARTURE_TIME");
                    tbatime =  rs1.getString("ARRIVAL_TIME");
                    tberate =  rs1.getInt("Economoy");
                    tbbrate =  rs1.getInt("Business_class");
                    tbacrate =  rs1.getInt("AC_parlour");
                    tbeseats =  rs1.getInt("Economoy_seats");
                    tbbseats =  rs1.getInt("Business_class_seats");
                    tbacseats =  rs1.getInt("AC_parlour_seats");
                    Object schtbData[] = {tbtrainid,tbtrainname,tbdeparture,tbarrival,tbdate,tbdtime,tbatime,tberate
                            ,tbbrate,tbacrate,tbeseats,tbbseats,tbacseats};
                    DefaultTableModel schtblmodel= (DefaultTableModel) tabledata.getModel();
                    schtblmodel.addRow(schtbData);
                   }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(management.this, e);
            }
        }
        else{
             lblerror.setText("Train Route Uploaded");
            try {
                Connection con = dbcon.getcon();
                String stm = "insert  into train_schedulle  values(?,?,?,?,?,?,?,?,?,?,?,?,?)";
                PreparedStatement sttm = con.prepareStatement(stm);
                sttm.setString(1,trainid);
                sttm.setString(2,trainname);
                sttm.setString(3,departure);
                sttm.setString(4,arrival);
                sttm.setString(5,date);
                sttm.setString(6,dtime);
                sttm.setString(7,atime);
                sttm.setString(8,erate);
                sttm.setString(9,brate);
                sttm.setString(10,acrate);
                sttm.setString(11,eseats);
                sttm.setString(12,bseats);
                sttm.setString(13,acseats);
                sttm.execute();
                Statement stm1 = con.createStatement();
                String s1 = "select * from train_schedulle";
                ResultSet rs1 = stm1.executeQuery(s1);
                while(rs1.next()){
                    tbtrainid =  rs1.getString("TRAIN_ID");
                    tbtrainname =  rs1.getString("TRAIN_NAME");
                    tbdeparture =  rs1.getString("DEPARTURE");
                    tbarrival =  rs1.getString("ARRIVAL");
                    tbdate =  rs1.getString("DATE");
                    tbdtime =  rs1.getString("DEPARTURE_TIME");
                    tbatime =  rs1.getString("ARRIVAL_TIME");
                    tberate =  rs1.getInt("Economoy");
                    tbbrate =  rs1.getInt("Business_class");
                    tbacrate =  rs1.getInt("AC_parlour");
                    tbeseats =  rs1.getInt("Economoy_seats");
                    tbbseats =  rs1.getInt("Business_class_seats");
                    tbacseats =  rs1.getInt("AC_parlour_seats");
                    Object schtbData[] = {tbtrainid,tbtrainname,tbdeparture,tbarrival,tbdate,tbdtime,tbatime,
                        tberate,tbbrate,tbacrate,tbeseats,tbbseats,tbacseats};
                    DefaultTableModel schtblmodel= (DefaultTableModel) tabledata.getModel();
                    schtblmodel.addRow(schtbData);
                   }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(management.this, e);
            }
        }
    }//GEN-LAST:event_btninsertMouseReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            Connection con = dbcon.getcon();
            Statement stm1 = con.createStatement();
            Statement stm2 = con.createStatement();
            String s1 = "select * from train_schedulle";
            ResultSet rs1 = stm1.executeQuery(s1);
            while(rs1.next()){
                    wintrainid =  rs1.getString("TRAIN_ID");
                    wintrainname =  rs1.getString("TRAIN_NAME");
                    windeparture =  rs1.getString("DEPARTURE");
                    winarrival =  rs1.getString("ARRIVAL");
                    windate =  rs1.getString("DATE");
                    windtime =  rs1.getString("DEPARTURE_TIME");
                    winatime =  rs1.getString("ARRIVAL_TIME");
                    winerate =  rs1.getInt("Economoy");
                    winbrate =  rs1.getInt("Business_class");
                    winacrate =  rs1.getInt("AC_parlour");
                    wineseats =  rs1.getInt("Economoy_seats");
                    winbseats =  rs1.getInt("Business_class_seats");
                    winacseats =  rs1.getInt("AC_parlour_seats");
                    Object schtbData[] = {wintrainid,wintrainname,windeparture,winarrival,windate,windtime,
                        winatime,winerate,winbrate,winacrate,wineseats,winbseats,winacseats};
                    DefaultTableModel schtblmodel= (DefaultTableModel) tabledata.getModel();
                    schtblmodel.addRow(schtbData);
                   }
            String s2 = "SELECT `Ticket_id`, `Name`, `CNIC`, `Contact_Number`, `Email_Address`, `Fare`, `Class`,"
                    + " `number_of_seats`, `From`, `to`, `date`, `train_id`, `departure_time`, `arrival_time`,"
                    + " `train_name` FROM `booking`";
            ResultSet rs2 = stm1.executeQuery(s2);
            while(rs2.next()){
                bticketid = rs2.getString("Ticket_id");
                bname = rs2.getString("Name");
                bcnic = rs2.getString("CNIC");
                bnumber = rs2.getString("Contact_Number");
                bemail = rs2.getString("Email_Address");
                bfare = rs2.getString("Fare");
                bclass = rs2.getString("Class");
                bookseats = rs2.getString("number_of_seats");
                bfrom = rs2.getString("From");
                bto = rs2.getString("to");
                bdate = rs2.getString("date");
                btrainid = rs2.getString("train_id");
                btrainname = rs2.getString("train_name");
                bdtime = rs2.getString("departure_time");
                batime = rs2.getString("arrival_time");
                Object book[] = {bticketid,bname,bcnic,bnumber,bemail,bfare,bclass,bookseats,bfrom,bto,bdate,
                    btrainid,btrainname,bdtime,batime};
                    DefaultTableModel schtblmodel= (DefaultTableModel) tblbooking.getModel();
                    schtblmodel.addRow(book);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(management.this, e);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btndeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndeleteMouseClicked
        int i =tabledata.getSelectedRow();
        id = (String)tabledata.getValueAt( i, 0);
        try {
            Connection con = dbcon.getcon();
            Statement stm = con.createStatement();
            stm.executeUpdate("delete from train_schedulle Where TRAIN_ID = '"+id+"'");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(management.this, e);
        }
        lblerror.setText("Route has been successfully deleted");
        btnrefresh.setVisible(true);
        btndelete.setVisible(false);
    }//GEN-LAST:event_btndeleteMouseClicked

    private void btnrefreshMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMousePressed
        tabledata.setModel(new DefaultTableModel(null, new String[]{"Train ID","train name","departure","arrival","date","departure Time","Arrival Time","Economy rate","Business rate","AC Parlour rate","Economy seats","Business seats","AC Parlour seats"}));
    }//GEN-LAST:event_btnrefreshMousePressed

    private void btnrefreshMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrefreshMouseReleased
         try {
            Connection con = dbcon.getcon();
            Statement stm = con.createStatement();
            String select = "select * from train_schedulle";
                ResultSet rs1 = stm.executeQuery(select);
                while(rs1.next()){
                    tbtrainid =  rs1.getString("TRAIN_ID");
                    tbtrainname =  rs1.getString("TRAIN_NAME");
                    tbdeparture =  rs1.getString("DEPARTURE");
                    tbarrival =  rs1.getString("ARRIVAL");
                    tbdate =  rs1.getString("DATE");
                    tbdtime =  rs1.getString("DEPARTURE_TIME");
                    tbatime =  rs1.getString("ARRIVAL_TIME");
                    tberate =  rs1.getInt("Economoy");
                    tbbrate =  rs1.getInt("Business_class");
                    tbacrate =  rs1.getInt("AC_parlour");
                    tbeseats =  rs1.getInt("Economoy_seats");
                    tbbseats =  rs1.getInt("Business_class_seats");
                    tbacseats =  rs1.getInt("AC_parlour_seats");
                    Object schtbData[] = {tbtrainid,tbtrainname,tbdeparture,tbarrival,tbdate,tbdtime,tbatime,
                        tberate,tbbrate,tbacrate,tbeseats,tbbseats,tbacseats};
                    DefaultTableModel schtblmodel= (DefaultTableModel) tabledata.getModel();
                    schtblmodel.addRow(schtbData);
                   }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(management.this, e);
        }
        lblerror.setText(null);
        btnrefresh.setVisible(false);
        btndelete.setVisible(true);
    }//GEN-LAST:event_btnrefreshMouseReleased

    private void managepanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managepanelMouseClicked
        pnlmanage.setVisible(true);
        pnlbooking.setVisible(false);
    }//GEN-LAST:event_managepanelMouseClicked

    private void bookingpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookingpanelMouseClicked
        pnlmanage.setVisible(false);
        pnlbooking.setVisible(true);
    }//GEN-LAST:event_bookingpanelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bookingpanel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninsert;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblerror;
    private javax.swing.JPanel managepanel;
    private javax.swing.JPanel pnlbooking;
    private javax.swing.JPanel pnlmanage;
    private javax.swing.JPanel pnlside;
    private javax.swing.JPanel pnltop;
    private javax.swing.JTable tabledata;
    private javax.swing.JTable tblbooking;
    private javax.swing.JTextField txtfacrate;
    private javax.swing.JTextField txtfacseats;
    private javax.swing.JTextField txtfarrival;
    private javax.swing.JTextField txtfatime;
    private javax.swing.JTextField txtfbrate;
    private javax.swing.JTextField txtfbseats;
    private javax.swing.JTextField txtfdate;
    private javax.swing.JTextField txtfdeparture;
    private javax.swing.JTextField txtfdtime;
    private javax.swing.JTextField txtferate;
    private javax.swing.JTextField txtfeseats;
    private javax.swing.JTextField txtftrainid;
    private javax.swing.JTextField txtftrainname;
    // End of variables declaration//GEN-END:variables
}