/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;
import db.dbcon;
import java.awt.Color;
import java.awt.Frame;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author Ahmar
 */
public class welcome extends javax.swing.JFrame {

    int xx, xy;

    /**
     * Creates new form welcome
     */
    public welcome() {
        initComponents();
        welcome.this.getRootPane().setBorder(new LineBorder(new Color(23,42,48)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        maintop = new javax.swing.JPanel();
        welcome = new javax.swing.JLabel();
        btnmaximize = new javax.swing.JLabel();
        btnminimize = new javax.swing.JLabel();
        btnclose = new javax.swing.JLabel();
        image = new javax.swing.JLabel();
        admin = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        usernameLine = new javax.swing.JSeparator();
        paaswordLine = new javax.swing.JSeparator();
        password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        error = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btncontinue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("welcome");
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainpanel.setBackground(new java.awt.Color(242, 242, 242));
        mainpanel.setForeground(new java.awt.Color(153, 153, 255));

        maintop.setBackground(new java.awt.Color(23, 42, 48));
        maintop.setAlignmentX(0.0F);
        maintop.setAlignmentY(0.0F);
        maintop.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        maintop.setName(""); // NOI18N
        maintop.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                maintopMouseDragged(evt);
            }
        });
        maintop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maintopMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                maintopMousePressed(evt);
            }
        });
        maintop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcome.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        welcome.setForeground(new java.awt.Color(253, 253, 255));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        welcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/train logo.png"))); // NOI18N
        welcome.setText("Train Management System");
        maintop.add(welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 30));

        btnmaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restore.png"))); // NOI18N
        btnmaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnmaximizeMouseReleased(evt);
            }
        });
        maintop.add(btnmaximize, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, -1, 30));

        btnminimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimize.png"))); // NOI18N
        btnminimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnminimizeMouseReleased(evt);
            }
        });
        maintop.add(btnminimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, -1, 30));

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cross.png"))); // NOI18N
        btnclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btncloseMouseReleased(evt);
            }
        });
        maintop.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, 30));

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pexels-vlad-bagacian-1444109.jpg"))); // NOI18N
        image.setAlignmentY(0.0F);

        admin.setBackground(new java.awt.Color(242, 242, 242));

        username.setBackground(new java.awt.Color(242, 242, 242));
        username.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        username.setForeground(new java.awt.Color(94, 90, 91));
        username.setBorder(null);

        usernameLine.setForeground(new java.awt.Color(49, 54, 56));

        paaswordLine.setForeground(new java.awt.Color(49, 54, 56));

        password.setBackground(new java.awt.Color(242, 242, 242));
        password.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        password.setForeground(new java.awt.Color(94, 90, 91));
        password.setToolTipText("");
        password.setBorder(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 54, 56));
        jLabel1.setText("password");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(49, 54, 56));
        jLabel2.setText("username");

        error.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        error.setForeground(new java.awt.Color(255, 51, 51));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 63, 65));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ADMIN");

        btnlogin.setBackground(new java.awt.Color(23, 42, 48));
        btnlogin.setForeground(new java.awt.Color(253, 253, 253));
        btnlogin.setText("Log in");
        btnlogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 42, 48), 6, true));
        btnlogin.setBorderPainted(false);
        btnlogin.setFocusPainted(false);
        btnlogin.setFocusable(false);
        btnlogin.setOpaque(true);
        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminLayout.createSequentialGroup()
                                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(usernameLine, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(username, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminLayout.createSequentialGroup()
                                    .addGap(24, 24, 24)
                                    .addComponent(paaswordLine, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(adminLayout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usernameLine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paaswordLine, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnlogin)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 63, 65));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("BOOKING");

        jLabel5.setBackground(new java.awt.Color(242, 242, 242));
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("For ticket reservation and timings");

        btncontinue.setBackground(new java.awt.Color(23, 42, 48));
        btncontinue.setForeground(new java.awt.Color(253, 253, 253));
        btncontinue.setText("continue");
        btncontinue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(23, 42, 48), 6, true));
        btncontinue.setBorderPainted(false);
        btncontinue.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btncontinue.setFocusPainted(false);
        btncontinue.setFocusable(false);
        btncontinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncontinueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(maintop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                                .addComponent(btncontinue, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)))
                .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addComponent(maintop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(mainpanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncontinue)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
        );

        getContentPane().add(mainpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 390));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked
        String dbpass = "";
        String user = username.getText();
        String pass = password.getText();
        PreparedStatement ps = null;
             ResultSet rs = null; 
        try{
             Connection conect = dbcon.getcon();
             Statement stm = conect.createStatement();
             String id =("select * from login where username ='"+user+"'" );
             rs = stm.executeQuery(id);
             while(rs.next()){
                 dbpass = rs.getString("Pass");
             }
           } catch (Exception e) {
               JOptionPane.showMessageDialog(welcome.this, e);
        }if(username.getText().trim().isEmpty() || password.getText().trim().isEmpty()){
            error.setText("Please Enter Username and Password");
        }
        else if(password.getText().equals(dbpass)) {
            new management().setVisible(true);
        } else {
            error.setText("Invalid username or password. Try again !");
            error.setForeground(Color.red);
        }
    }//GEN-LAST:event_btnloginMouseClicked
    
    private void btncontinueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncontinueMouseClicked
        new trainMS().setVisible(true);
    }//GEN-LAST:event_btncontinueMouseClicked

    private void btnminimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizeMouseReleased
        welcome.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_btnminimizeMouseReleased

    private void btnmaximizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnmaximizeMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnmaximizeMouseReleased

    private void btncloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncloseMouseReleased
        System.exit(0);
    }//GEN-LAST:event_btncloseMouseReleased

    private void maintopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintopMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_maintopMousePressed

    private void maintopMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintopMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_maintopMouseDragged

    private void maintopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maintopMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            if (welcome.this.getExtendedState() == Frame.MAXIMIZED_BOTH) {
                welcome.this.setExtendedState(JFrame.NORMAL);
            } else {
                welcome.this.setExtendedState(WIDTH);
            }
        }
    }//GEN-LAST:event_maintopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private javax.swing.JLabel btnclose;
    private javax.swing.JButton btncontinue;
    private javax.swing.JButton btnlogin;
    private javax.swing.JLabel btnmaximize;
    private javax.swing.JLabel btnminimize;
    private javax.swing.JLabel error;
    private javax.swing.JLabel image;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JPanel maintop;
    private javax.swing.JSeparator paaswordLine;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    private javax.swing.JSeparator usernameLine;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
